### PR TITLE
Create pt.json

### PR DESCRIPTION
**Pull request by ViPeR5000**

### CODE REVIEW

**Comment by MiguelAngelLV** [comment]
Thanks you for the translation.

I will release soon a new update with sensors name translatable too

**Comment by ViPeR5000** [comment]
> Thanks you for the translation.
> 
> I will release soon a new update with sensors name translatable too

Then i will update my  translation thks for the integration

**Comment by MiguelAngelLV** [comment]
One question.

In Spain we have off peak in spanish holidays (06 of december for example). How works in Portugal?

Do you need add a holiday selector?

**Comment by ViPeR5000** [comment]
we dont have that option in portugal.

**Comment by MiguelAngelLV** [comment]
So, do you only have by hour and weekends or only by hour?

**Pull request merged**
